apiVersion: v1
kind: Pod
metadata:
  name: nginx-mealie
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
  volumes:
    - name: scratch-volume
      persistentVolumeClaim:
        claimName: mealie-data
